version: "3"
services:
  backend:
    build: backend
    container_name: backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      DB_HOST: mariadb
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      PORT: ${BACKEND_PORT}
      INDEXER_ENABLED: ${INDEXER_ENABLED}
      INDEXER_START_BLOCK: ${INDEXER_START_BLOCK}
      INDEXER_END_BLOCK: ${INDEXER_END_BLOCK}
      INDEXER_BATCH_SIZE: ${INDEXER_BATCH_SIZE}
      INDEXER_JSON_RPC_URL: ${INDEXER_JSON_RPC_URL}
      FETCHER_ENABLED: ${FETCHER_ENABLED}
      FETCHER_GITHUB_TOKEN: ${FETCHER_GITHUB_TOKEN}
      ATTESTER_ENABLED: ${ATTESTER_ENABLED}
      ATTESTER_PRIVATE_KEY: ${ATTESTER_PRIVATE_KEY}
      ATTESTER_JSON_RPC_URL: ${ATTESTER_JSON_RPC_URL}
    networks:
      - db-service
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    container_name: db
    ports:
      - "3306:${DB_PORT}"
    environment: 
      MARIADB_ROOT_PASSWORD: ${DB_PASS}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
    networks:
      - db-service
    volumes:
      - maria-data:/data/db

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:${ADMINER_PORT}"
    networks:
      - db-service
    depends_on:
      - mariadb

networks:
  db-service:
    driver: bridge

volumes:
  maria-data:
    driver: local